services:
  - type: web
    name: cupstone-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: MONGO_URI
        value: "mongodb+srv://gabristack:Gabbo2611@cluster0.xyc1oxa.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      - key: PORT
        value: "3001"
